# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fathom < Formula
  desc "Repository impact analysis for Pull Requests. Know what a PR actually touches."
  homepage "https://github.com/blak0p/Fathom"
  version "0.0.1"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/blak0p/Fathom/releases/download/v0.0.1/fathom_0.0.1_linux_amd64.tar.gz"
    sha256 "c5bd12c9b8a21779919a215d4e66ead48eff2d94828deeb177c01cce2119da0c"
    define_method(:install) do
      bin.install "fathom"
    end
  end

  test do
    system "#{bin}/fathom --version"
  end
end
