# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCourer < Formula
  desc "AI-powered local git operations via MCP. Zero cloud tokens for git."
  homepage "https://github.com/blak0p/git-courer"
  version "2.5.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/blak0p/git-courer/releases/download/v2.5.0/git-courer_2.5.0_linux_amd64.tar.gz"
    sha256 "e2aae2f8d6174f36dc60d7aae409e0fa431e63e1ee9dd4801cc0b65c872cb002"
    define_method(:install) do
      bin.install "git-courer"
    end
  end

  test do
    system "#{bin}/git-courer --version"
  end
end
